when:
  event:
    - manual
    - push
  branch: main
  path:
    - .woodpecker/deploy.yaml
    - Dockerfile
    - go.mod
    - go.sum
    - cmd/**
    - internal/**
    - Makefile

steps:
  image:
    image: kokuwaio/buildctl:v0.28.0
    settings:
      platform: linux/amd64
      name: git.grayc.dev/grayc-devops/helm-manifest-renderer:latest
      auth:
        git.grayc.dev:
          username: {from_secret: CONTAINER_REGISTRY_USERNAME}
          password: {from_secret: CONTAINER_REGISTRY_PASSWORD}

  image-dockerhub:
    image: kokuwaio/buildctl:v0.28.0
    settings:
      platform: linux/amd64
      name: docker.io/graycgmbh/helm-manifest-renderer:latest
      auth:
        "https://index.docker.io/v1/":
          username: {from_secret: DOCKERHUB_USERNAME}
          password: {from_secret: DOCKERHUB_TOKEN}
